name: 'loki-action-jira-to-github'
description: 'Synchronizes Jira issues to GitHub repositories'
inputs:
  from-jira:
    description: 'Jira used as a source to synchronize isuses'
    required: true
  to-repo:
    description: 'The destination repository'
    required: true
  jql:
    description: 'JQL used to search for issues to synchronize'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.from-jira }}
    - ${{ inputs.to-repo }}
    - ${{ inputs.jql }}
